"""empty message

Revision ID: aced77a5fced
Revises: 07823444eafa
Create Date: 2020-10-01 18:34:44.365361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aced77a5fced'
down_revision = '07823444eafa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('artists', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('shows', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('shows', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('venues', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('venues', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'updated_at')
    op.drop_column('venues', 'created_at')
    op.drop_column('shows', 'updated_at')
    op.drop_column('shows', 'created_at')
    op.drop_column('artists', 'updated_at')
    op.drop_column('artists', 'created_at')
    # ### end Alembic commands ###
